### ISSUE TITLE
Adding Xbox and Xbox 360

### ISSUE THREAD

**Issue by Boleros07** [RetroHursty69/es-theme-magazinemadness2#2]
Love the theme. Works amazingly and the custom sets are great too. Way more than the usual theme.

Any chance you could add Xbox and Xbox 360? Mario Kart would be a sick collection too.

I know it’s a crazy old project so probably not but I saw you added PS3 a couple months ago and thought I’d ask.

Thanks again for the awesome theme!

**Comment by RetroHursty69** [comment]
Hi. I am really scaling back on theme making and almost retired from it tbh.
Magazine Madness 2 requires a bit of work to make those magazine covers.
No promises, but I will try and find the motivation.
I will email you if I do.

Cheers
Hursty

**Comment by Boleros07** [comment]
Appreciate the quick response!

Yeah I figured they were pretty involved so no worries if it’s too much.

**Comment by RetroHursty69** [comment]
Hi

I have just added:

xbox
xbox360
mariokart

Hope you enjoy it.

Cheers
Hursty

**Comment by Boleros07** [comment]
Wow!

 So quick! Thank you so much!

They’re amazing!
